version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_omni
    restart: always
    environment:
      POSTGRES_DB: omni
      POSTGRES_USER: omni
      POSTGRES_PASSWORD: omni
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - omni_network

  redis:
    image: redis:8-alpine
    container_name: redis_omni
    restart: always
    ports:
      - "6379:6379"
    networks:
      - omni_network

volumes:
  postgres_data:

networks:
  omni_network:
    driver: bridge